### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by kaiq663** [cszhilu1998/SelfDZSR#11]
I try the demo image(from Nikon) you provided, it works well, which produces right Ref, LR and GT.

But I instead pick  random images from original CameraFusion (images are shown in your CameraFusion), specifically, LR(wide) CameraFusion\train\LR\x1\IMG_2280.jpg(3024 * 4032) and Ref(telephoto) CameraFusion\train\Ref\x1(3024 * 4032) .

It didn't warp well. 

Which configuartion should I modify?or something wrong with me?
![camera_warp_HR](https://github.com/cszhilu1998/SelfDZSR/assets/31822398/ae37891f-2d91-43b4-9654-5da3a660c376)

**Comment by cszhilu1998** [comment]
This may be due to the problem with the alignment method (PWC-Net). You can use x2~x8 downsampled images to calculate optical flow, which may be more stable. More advanced or robust alignment methods can also be tried.
Besides, the data pre-processing code is only for x4 zoom, some changes may be needed for other zooms.

**Comment by kaiq663** [comment]
Hi, having done what I know, : ( 

Before, keep all defalut settings, because I have no idea to do changes for other zoom, for Nikon(85/18), for CameraFusion(6.0/4.25), how to make changes?

Firstly, I take x2 image in original CameraFusion dataset, specically LR(wide) CameraFusion\train\LR\x2\IMG_2280.jpg(1512 * 2016) and Ref(telephoto) CameraFusion\train\Ref\x2(1512*2016) . It produces much more better result, yet still cannot produce LR,HR,REF, it warns me needs to be removed more boundaries, I don't know how to do that.Here is the image.
![image](https://github.com/cszhilu1998/SelfDZSR/assets/31822398/43738322-66c8-495e-861f-e71a184750ee)


Secondly, inspired by this, I use matlab(imresize) to produce x2,x4,x8 corresponding images.Unfortunately, they all work bad, like this.
![image](https://github.com/cszhilu1998/SelfDZSR/assets/31822398/d601a0af-0873-49f8-ad24-0f6f6c0e03a5)

Thirdly, it seems that origial CameraFusion dataset do not produce x2 via matlab, otherwise it shoule be the same.

**Comment by cszhilu1998** [comment]
Have you followed this [readme](https://github.com/cszhilu1998/SelfDZSR/blob/master/data_preprocess/README.md)? Maybe you should first crop out the center areas of short-focus images.
Additionally, in the Line 340 of [alignment code](https://github.com/cszhilu1998/SelfDZSR/blob/master/data_preprocess/position_alignment/pwc_net.py), in order to make the size ratio of the generated telephoto and short-focus images to be an integral multiple, we resize the telephoto image. You can try to change this to meet your own needs.

**Comment by cszhilu1998** [comment]
And you can change 'down_sampling_factor' in the Line 334 of [alignment code](https://github.com/cszhilu1998/SelfDZSR/blob/master/data_preprocess/position_alignment/pwc_net.py) for adjusting the downsampling ratio.

**Comment by kaiq663** [comment]
I make a mistake in imresize of matlab, saving .jpg instead of .png, and I correct it.

In your article, The focal length ratio between the telephoto and short-focal images is ∼2. Thus, it can constitute a ×2 DZSR dataset. Do you mean that you take x2 CameraFusion images(1512 * 2016) to preprocess instead of x1(3024 * 4032).

If so(I take the x2 CameraFusion images)  

I follow your readme to crop out the center areas of short-focus images, for CameraFusion the focal length is
![image](https://github.com/cszhilu1998/SelfDZSR/assets/31822398/c4daedaa-67f0-4f02-94e7-90556d2e11ee)

Those are for Nikon, x4 dataset. What number should I change for CameraFusion, I try a few number, they fails.
![image](https://github.com/cszhilu1998/SelfDZSR/assets/31822398/0df9ea37-b15a-47f5-8e3f-2d5c9428ba11)
![image](https://github.com/cszhilu1998/SelfDZSR/assets/31822398/85661074-a0ec-448f-b27c-3e89385060b2)

And there seems to have a variant in color_alignment, What should I change for this?
![image](https://github.com/cszhilu1998/SelfDZSR/assets/31822398/23778e2b-9d02-46eb-8052-cd8f5b20da13)

**Comment by cszhilu1998** [comment]
I’m sorry for ignoring you. I just discovered this problem when I checked the code. Please let me know if there are still problems now.
