### ISSUE TITLE
Question about borderline

### ISSUE THREAD

**Issue by hzluyali** [cszhilu1998/SelfDZSR#4]
Thank you for your impressive code. I have tried to reappear your method by directly runing sh test_camerafusion.sh. However, I find that borderline exists in output images, and some regions are warped. How to deal with this issue?

**Comment by cszhilu1998** [comment]
If the borderline between the middle and surrounding areas is obvious or some areas in the middle are warped, you can set "--paste False". This operation will not paste the telephoto image into the middle of the short-focus image.
If the borderline is caused by patch-based testing, you can try to test with the full-resolution image, but it will take a lot of CUDA memory. In fact, we have taken some tricks to mitigate borderline effects as much as possible (see [issue 2](https://github.com/cszhilu1998/SelfDZSR/issues/2)), but it may be not perfect.
